#!/usr/bin/env node
/**
 * Translate the deployment's environment variables into dsh configuration.
 *
 * Produces, under $DSH_HOME:
 *   settings.yaml      — the `llm-pi-ai` route plus the default model
 *   .credentials.yaml  — the API key, referenced by name from settings.yaml
 *
 * The OpenAI-compatible route is `dsh-llm-pi-ai`: it is the adapter that
 * speaks `openai-completions` and accepts an arbitrary baseURL, which is what
 * an intranet vLLM / SGLang / Ollama / one-api gateway exposes.
 *
 * A file we generated carries GENERATED_MARKER; if a human has since edited it
 * (marker removed) it is left alone, so hand-tuning and the Web UI both win.
 */
import fs from 'node:fs'
import path from 'node:path'
import yaml from 'js-yaml'

const GENERATED_MARKER = '# Generated by dsh-docker from environment variables.'
const DSH_HOME = process.env.DSH_HOME ?? '/data/dsh-home'
const SETTINGS = path.join(DSH_HOME, 'settings.yaml')
const CREDENTIALS = path.join(DSH_HOME, '.credentials.yaml')

const env = process.env
const bool = (value, fallback) => (value === undefined ? fallback : /^(1|true|yes|on)$/iu.test(value))

function fail(message) {
  process.stderr.write(`[config] ${message}\n`)
  process.exit(1)
}

const baseUrl = env.DSH_LLM_BASE_URL
if (!baseUrl) {
  fail('DSH_LLM_BASE_URL is required (e.g. http://10.0.0.5:8000/v1)')
}

const provider = env.DSH_LLM_PROVIDER || 'intranet'
const providerLabel = env.DSH_LLM_PROVIDER_LABEL || '内网 DeepSeek'
const defaultModel = env.DSH_LLM_MODEL || 'deepseek-chat'
const contextWindow = Number(env.DSH_LLM_CONTEXT_WINDOW || 131072)
const maxTokens = Number(env.DSH_LLM_MAX_TOKENS || 8192)

/** `a,b:Label B` → one entry per id, labelling the default model when given. */
function parseModels(spec, fallbackId) {
  const ids = (spec ?? '').split(',').map((s) => s.trim()).filter(Boolean)
  const list = ids.length > 0 ? ids : [fallbackId]
  return list.map((entry) => {
    const [id, label] = entry.split(':').map((s) => s.trim())
    return { id, name: label || id }
  })
}

const models = parseModels(env.DSH_LLM_MODELS, defaultModel)

// Only the switches the operator actually set are emitted, so dsh keeps its
// own defaults for everything else.
const compat = {}
if (env.DSH_LLM_SUPPORTS_DEVELOPER_ROLE !== undefined) {
  compat.supportsDeveloperRole = bool(env.DSH_LLM_SUPPORTS_DEVELOPER_ROLE, false)
}
if (env.DSH_LLM_MAX_TOKENS_FIELD) compat.maxTokensField = env.DSH_LLM_MAX_TOKENS_FIELD
if (env.DSH_LLM_THINKING_FORMAT) compat.thinkingFormat = env.DSH_LLM_THINKING_FORMAT

const route = {
  displayName: providerLabel,
  apiKeyEnv: 'DSH_INTRANET_LLM_KEY',
  api: 'openai-completions',
  baseURL: baseUrl,
  models: models.map((m) => ({ ...m, contextWindow, maxTokens })),
}
if (Object.keys(compat).length > 0) route.compat = compat
if (env.DSH_LLM_REASONING_EFFORT) route.reasoning = env.DSH_LLM_REASONING_EFFORT

const settings = {
  'llm-pi-ai': { providers: { [provider]: route } },
  'agent-default-model': { provider, model: models[0].id },
}

fs.mkdirSync(DSH_HOME, { recursive: true, mode: 0o700 })

/* ── settings.yaml ───────────────────────────────────────────────────────── */

const settingsBody = `${GENERATED_MARKER}\n${yaml.dump(settings, { lineWidth: 120, noRefs: true })}`
let writeSettings = true
if (fs.existsSync(SETTINGS)) {
  const current = fs.readFileSync(SETTINGS, 'utf8')
  if (!current.startsWith(GENERATED_MARKER)) {
    writeSettings = false
    process.stdout.write('[config] settings.yaml was hand-edited; leaving it untouched\n')
  } else if (current === settingsBody) {
    writeSettings = false
  }
}
if (writeSettings) {
  fs.writeFileSync(SETTINGS, settingsBody, { mode: 0o600 })
  process.stdout.write(`[config] wrote ${SETTINGS} (route "${provider}" → ${baseUrl})\n`)
}

/* ── .credentials.yaml ───────────────────────────────────────────────────── */
/* Merged rather than overwritten, so refs written by the Web UI survive. */

let credentials = { version: 1, refs: {} }
if (fs.existsSync(CREDENTIALS)) {
  try {
    const parsed = yaml.load(fs.readFileSync(CREDENTIALS, 'utf8'))
    if (parsed && typeof parsed === 'object' && parsed.refs) {
      credentials = { version: 1, refs: { ...parsed.refs }, ...(parsed.records ? { records: parsed.records } : {}) }
    }
  } catch {
    process.stderr.write('[config] existing .credentials.yaml is unreadable; rewriting it\n')
  }
}

const apiKey = env.DSH_LLM_API_KEY || 'sk-intranet'
if (!env.DSH_LLM_API_KEY) {
  process.stdout.write('[config] DSH_LLM_API_KEY unset; using a placeholder key\n')
}
if (credentials.refs.DSH_INTRANET_LLM_KEY !== apiKey) {
  credentials.refs.DSH_INTRANET_LLM_KEY = apiKey
  fs.writeFileSync(CREDENTIALS, yaml.dump(credentials, { noRefs: true }), { mode: 0o600 })
}

// dsh refuses to boot if the credential file is group/world readable.
fs.chmodSync(CREDENTIALS, 0o600)
fs.chmodSync(SETTINGS, 0o600)

process.stdout.write(`[config] default model: ${models[0].id} (via ${provider})\n`)
