#!/usr/bin/env node
/**
 * Translate the deployment's environment variables into dsh configuration.
 *
 * Produces, under $DSH_HOME:
 *   settings.yaml      — the `llm-pi-ai` route plus the default model
 *   .credentials.yaml  — the API key, referenced by name from settings.yaml
 *
 * The OpenAI-compatible route is `dsh-llm-pi-ai`: it is the adapter that
 * speaks `openai-completions` and accepts an arbitrary baseURL, which is what
 * an intranet vLLM / SGLang / Ollama / one-api gateway exposes.
 *
 * Ownership split, chosen so that neither side silently loses work:
 *
 *   settings.yaml      seeded once per user, then owned by that user. dsh's
 *                      Models page writes here, so a colleague can pick their
 *                      own model. Set DSH_CONFIG_OVERWRITE=1 to take it back.
 *   .credentials.yaml  the key named by DSH_LLM_API_KEY is refreshed on every
 *                      start, so rotating a leaked key propagates to everyone
 *                      without touching individual users. Other refs are kept.
 */
import fs from 'node:fs'
import path from 'node:path'
import yaml from 'js-yaml'

const GENERATED_MARKER = '# Generated by dsh-docker from environment variables.'
const DSH_HOME = process.env.DSH_HOME ?? '/data/dsh-home'
const SETTINGS = path.join(DSH_HOME, 'settings.yaml')
const CREDENTIALS = path.join(DSH_HOME, '.credentials.yaml')

const env = process.env
const bool = (value, fallback) => (value === undefined ? fallback : /^(1|true|yes|on)$/iu.test(value))

function fail(message) {
  process.stderr.write(`[config] ${message}\n`)
  process.exit(1)
}

const baseUrl = env.DSH_LLM_BASE_URL
if (!baseUrl) {
  fail('DSH_LLM_BASE_URL is required (e.g. http://10.0.0.5:8000/v1)')
}

const provider = env.DSH_LLM_PROVIDER || 'intranet'
const providerLabel = env.DSH_LLM_PROVIDER_LABEL || '内网 DeepSeek'
const defaultModel = env.DSH_LLM_MODEL || 'deepseek-chat'
const contextWindow = Number(env.DSH_LLM_CONTEXT_WINDOW || 131072)
const maxTokens = Number(env.DSH_LLM_MAX_TOKENS || 8192)

/** `a,b:Label B` → one entry per id, labelling the default model when given. */
function parseModels(spec, fallbackId) {
  const ids = (spec ?? '').split(',').map((s) => s.trim()).filter(Boolean)
  const list = ids.length > 0 ? ids : [fallbackId]
  return list.map((entry) => {
    const [id, label] = entry.split(':').map((s) => s.trim())
    return { id, name: label || id }
  })
}

const models = parseModels(env.DSH_LLM_MODELS, defaultModel)

// Only the switches the operator actually set are emitted, so dsh keeps its
// own defaults for everything else.
const compat = {}
if (env.DSH_LLM_SUPPORTS_DEVELOPER_ROLE !== undefined) {
  compat.supportsDeveloperRole = bool(env.DSH_LLM_SUPPORTS_DEVELOPER_ROLE, false)
}
if (env.DSH_LLM_MAX_TOKENS_FIELD) compat.maxTokensField = env.DSH_LLM_MAX_TOKENS_FIELD
if (env.DSH_LLM_THINKING_FORMAT) compat.thinkingFormat = env.DSH_LLM_THINKING_FORMAT

const route = {
  displayName: providerLabel,
  apiKeyEnv: 'DSH_INTRANET_LLM_KEY',
  api: 'openai-completions',
  baseURL: baseUrl,
  models: models.map((m) => ({ ...m, contextWindow, maxTokens })),
}
if (Object.keys(compat).length > 0) route.compat = compat
if (env.DSH_LLM_REASONING_EFFORT) route.reasoning = env.DSH_LLM_REASONING_EFFORT

const settings = {
  'llm-pi-ai': { providers: { [provider]: route } },
  'agent-default-model': { provider, model: models[0].id },
}

fs.mkdirSync(DSH_HOME, { recursive: true, mode: 0o700 })

/* ── settings.yaml ───────────────────────────────────────────────────────── */

/*
 * The environment seeds a user's settings.yaml ONCE; after that the user owns
 * it, because dsh's own Models page writes here.
 *
 * A marker comment cannot be used to tell "generated" from "user-edited":
 * dsh's settings writer is comment-preserving, so a UI edit keeps the marker
 * and the next instance start would silently revert the user's change. That is
 * why the rule below keys off the file merely existing, not off its contents.
 *
 * DSH_CONFIG_OVERWRITE=1 switches to admin-managed mode: regenerate on every
 * start, so nobody can keep a local override.
 */
const settingsBody = `${GENERATED_MARKER}\n${yaml.dump(settings, { lineWidth: 120, noRefs: true })}`
const overwrite = process.env.DSH_CONFIG_OVERWRITE === '1'

if (fs.existsSync(SETTINGS) && !overwrite) {
  process.stdout.write('[config] settings.yaml already exists; keeping it (user changes preserved)\n')
} else {
  fs.writeFileSync(SETTINGS, settingsBody, { mode: 0o600 })
  process.stdout.write(`[config] wrote ${SETTINGS} (route "${provider}" → ${baseUrl})\n`)
}

/* ── .credentials.yaml ───────────────────────────────────────────────────── */
/* Merged rather than overwritten, so refs written by the Web UI survive. */

let credentials = { version: 1, refs: {} }
if (fs.existsSync(CREDENTIALS)) {
  try {
    const parsed = yaml.load(fs.readFileSync(CREDENTIALS, 'utf8'))
    if (parsed && typeof parsed === 'object' && parsed.refs) {
      credentials = { version: 1, refs: { ...parsed.refs }, ...(parsed.records ? { records: parsed.records } : {}) }
    }
  } catch {
    process.stderr.write('[config] existing .credentials.yaml is unreadable; rewriting it\n')
  }
}

const apiKey = env.DSH_LLM_API_KEY || 'sk-intranet'
if (!env.DSH_LLM_API_KEY) {
  process.stdout.write('[config] DSH_LLM_API_KEY unset; using a placeholder key\n')
}
if (credentials.refs.DSH_INTRANET_LLM_KEY !== apiKey) {
  const replacing = credentials.refs.DSH_INTRANET_LLM_KEY !== undefined
  credentials.refs.DSH_INTRANET_LLM_KEY = apiKey
  fs.writeFileSync(CREDENTIALS, yaml.dump(credentials, { noRefs: true }), { mode: 0o600 })
  // Say so explicitly: silently replacing a credential is how a user ends up
  // wondering why the key they set in the UI stopped working.
  process.stdout.write(replacing
    ? '[config] refreshed the managed API key from the environment (DSH_LLM_API_KEY)\n'
    : '[config] stored the API key from the environment\n')
}

// dsh refuses to boot if the credential file is group/world readable.
fs.chmodSync(CREDENTIALS, 0o600)
fs.chmodSync(SETTINGS, 0o600)

process.stdout.write(`[config] default model: ${models[0].id} (via ${provider})\n`)
